import { signBodyV2 } from "./signing";
import { AGENT_API_PATHS } from "./agent-api-paths";
import { fetchWithRetrySigned } from "./fetch-error";

export interface ScanPayload {
  /**
   * UUID generated by the agent at the moment the raw scan is captured.
   * Stable across retries — the backend uses (agent_id, agent_event_id) as
   * the idempotency key so a retried POST returns the same event_id.
   */
  agent_event_id: string;
  scanner_device_code: string;
  port: string;
  raw_value: string;
  scanned_at: string;
  /** 'serial' from this agent; 'hid_keyboard'/'manual' come from the web UI. */
  source: "serial" | "hid_keyboard" | "manual";
  /**
   * Identity snapshot captured at scan time (VID/PID/serial/etc.). Lets
   * forensics tell which physical USB device produced a given scan, even
   * if the scanner is later rebound to another device_code.
   */
  device_identity_snapshot: Record<string, string> | null;
}

export interface SendResult {
  ok: boolean;
  status: number;
  body: unknown;
}

export async function sendScan(params: {
  backendUrl: string;
  agentCode: string;
  agentSecret: string;
  payload: ScanPayload;
}): Promise<SendResult> {
  const body = JSON.stringify(params.payload);
  const res = await fetchWithRetrySigned(
    `${params.backendUrl}${AGENT_API_PATHS.scans}`,
    () => ({
      method: "POST",
      headers: signBodyV2({
        agentCode: params.agentCode,
        agentSecret: params.agentSecret,
        method: "POST",
        canonicalPath: AGENT_API_PATHS.scans,
        body,
      }),
      body,
      redirect: "manual",
    }),
  );

  // A redirect means our request was intercepted (e.g. by an auth proxy)
  // and never reached the route. Treat it as a hard failure so we don't
  // silently log [OK] while no row is written.
  if (res.status >= 300 && res.status < 400) {
    return {
      ok: false,
      status: res.status,
      body: {
        error: "intercepted_redirect",
        location: res.headers.get("location"),
      },
    };
  }

  let parsed: unknown = null;
  const text = await res.text();
  if (text) {
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = { raw: text };
    }
  }

  return { ok: res.ok, status: res.status, body: parsed };
}
